# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inventory_shopping_cart_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%inventory_shopping_cart_service.proto\"%\n\x0fProductToSearch\x12\x12\n\nid_product\x18\x01 \x01(\x05\"2\n\x1bProductAvailabilityResponse\x12\x13\n\x0bstatus_code\x18\x01 \x01(\x08\x32X\n\x13ProductAvailability\x12\x41\n\rSearchProduct\x12\x10.ProductToSearch\x1a\x1c.ProductAvailabilityResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inventory_shopping_cart_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PRODUCTTOSEARCH._serialized_start=41
  _PRODUCTTOSEARCH._serialized_end=78
  _PRODUCTAVAILABILITYRESPONSE._serialized_start=80
  _PRODUCTAVAILABILITYRESPONSE._serialized_end=130
  _PRODUCTAVAILABILITY._serialized_start=132
  _PRODUCTAVAILABILITY._serialized_end=220
# @@protoc_insertion_point(module_scope)
