# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import inventory_shopping_cart_service_pb2 as inventory__shopping__cart__service__pb2


class ProductAvailabilityStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SearchProduct = channel.unary_unary(
                '/ProductAvailability/SearchProduct',
                request_serializer=inventory__shopping__cart__service__pb2.ProductToSearch.SerializeToString,
                response_deserializer=inventory__shopping__cart__service__pb2.ProductAvailabilityResponse.FromString,
                )


class ProductAvailabilityServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SearchProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProductAvailabilityServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SearchProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchProduct,
                    request_deserializer=inventory__shopping__cart__service__pb2.ProductToSearch.FromString,
                    response_serializer=inventory__shopping__cart__service__pb2.ProductAvailabilityResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ProductAvailability', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ProductAvailability(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SearchProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ProductAvailability/SearchProduct',
            inventory__shopping__cart__service__pb2.ProductToSearch.SerializeToString,
            inventory__shopping__cart__service__pb2.ProductAvailabilityResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
